CREATE DATABASE [$(KC_DB_NAME)];
GO

USE [$(KC_DB_NAME)];
GO

CREATE LOGIN [$(KC_DB_USERNAME)] WITH PASSWORD = '$(KC_DB_PASSWORD)';
GO

CREATE USER [$(KC_DB_USERNAME)] FOR LOGIN [$(KC_DB_USERNAME)];
GO

ALTER ROLE db_owner ADD MEMBER [$(KC_DB_USERNAME)];
GO
