-- webapp_db_init.sql

CREATE DATABASE [$(WA_DB_NAME)];
GO

USE [$(WA_DB_NAME)];
GO

CREATE LOGIN [$(WA_DB_USERNAME)] WITH PASSWORD = '$(WA_DB_PASSWORD)';
GO

CREATE USER [$(WA_DB_USERNAME)] FOR LOGIN [$(WA_DB_USERNAME)];
GO

ALTER ROLE db_owner ADD MEMBER [$(WA_DB_USERNAME)];
GO