version: '3.7'

services:
  webapp:
    build:
      context: .
      dockerfile: .\WebApplication1\Dockerfile
    image: webapp:latest
    ports:
      - "5001:5001"  # Map HTTP to 5001
      - "5002:5002"  # Map HTTPS to 5002
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5001;https://*:5002  # Set correct URLs
    depends_on:
      - mssql
      - mssql.keycloak.init 
      - keycloak

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_PID=Express
        - MSSQL_DATABASE=master
        - MSSQL_USER=sa
        - MSSQL_SA_PASSWORD=3@s#21V4pj97YPL
        - MSSQL_PASSWORD=3@s#21V4pj97YPL
    volumes:
      - mssql_data:/var/opt/mssqlwebapplication1
    ports:
      - "1433:1433"  # Expose MSSQL to the host on port 1433

  mssql.keycloak.init:
      image: mcr.microsoft.com/mssql/server:2022-latest
      volumes:
        - ./docker/init/keycloak:/docker-entrypoint-initdb.d  
      depends_on:
        - mssql
      command: >
         bash -c "
            # Wait for SQL Server to be available
            for i in {1..60}; do
              /opt/mssql-tools18/bin/sqlcmd -S mssql:1433 -U sa -P '3@s#21V4pj97YPL' -Q 'SELECT 1' -N o -C && break || sleep 2;
            done;
    
            # Run initialization script
            /opt/mssql-tools18/bin/sqlcmd -S mssql:1433 -U sa -P  '3@s#21V4pj97YPL' -d master -i /docker-entrypoint-initdb.d/init.sql -N o -C;
            echo 'All done!';"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080 
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mssql
      KC_DB_URL: jdbc:sqlserver://mssql:1433;databaseName=keycloak;encrypt=false
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 3@s#21V4pj97YPL
    ports:
      - 8080:8080 
    restart: always
    depends_on:
      - mssql
      - mssql.keycloak.init  

volumes:
  mssql_data:
    driver: local

networks:
  webapplication1-nw:
    driver: bridge
