version: '3.7'

services:
  webapp:
    build:
      context: .
      dockerfile: .\WebApplication1\Dockerfile
    image: webapp:latest
    ports:
      - "5001:5001"  # Map HTTP to 5001
      - "5002:5002"  # Map HTTPS to 5002
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5001;https://*:5002  # Set correct URLs
    depends_on:
      - mssql
      - keycloak

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_PID=Express
        - MSSQL_DATABASE=master
        - MSSQL_USER=sa
        - MSSQL_SA_PASSWORD=3@s#21V4pj97YPL
        - MSSQL_PASSWORD=3@s#21V4pj97YPL
    volumes:
      - mssql_data:/var/opt/mssqlkeycloak 
    ports:
      - "1433:1433"  # Expose MSSQL to the host on port 1433
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080 
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mssql
      KC_DB_URL: jdbc:sqlserver://mssql:1433;databaseName=master;encrypt=false
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: 3@s#21V4pj97YPL
    ports:
      - 8080:8080 
    restart: always
    depends_on:
      - mssql 
    networks:
      - keycloak_network

volumes:
  mssql_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge
